### PR TITLE
Add zarrita to implementations list

### PR DESCRIPTION
**Pull request by normanrz**

### CODE REVIEW

**Comment by joshmoore** [comment]
:100: Thoughts on delineating V3-only implementations?

**Comment by normanrz** [comment]
Zarrita also speaks V2: https://github.com/scalableminds/zarrita/blob/async/zarrita/array_v2.py

**Comment by joshmoore** [comment]
> Zarrita also speaks V2

TIL!

**Review by MSanKeys963 — APPROVED** [review]

**Comment by MSanKeys963** [comment]
Thanks for the PR, @normanrz.
LGTM.



> Thoughts on delineating V3-only implementations?

I can work on a separate table for V3 on the implementations page.

**Pull request merged**
