### PR TITLE
use index.md for subdirectory pages

### PR DESCRIPTION
**Pull request by joshmoore**
@MSanKeys963 this is what I meant with https://github.com/zarr-developers/zarr-developers.github.io/pull/78#discussion_r1184009677

### CODE REVIEW

**Comment by MSanKeys963** [comment]
Thanks for the PR, @joshmoore.

From your comment - Do you only want to rename the sub-directory pages to `index.md`, or are you proposing to change the front matter as well?

**Comment by joshmoore** [comment]
hmm... odd. Sorry, there should have been this diff:
```
@@ -2,7 +2,6 @@
 layout: single
 author_profile: false
 title: Zarr Community
-permalink: /community/
 sidebar:
   title: "Content"
   nav: sidebar
```

What did you try?

**Comment by MSanKeys963** [comment]
This is the same front matter currently in [community.md](https://github.com/zarr-developers/zarr-developers.github.io/edit/main/community/community.md).

I thought you wanted me to remove `layout: single` and `author_profile: false` from the front matter, which won't work as `layout: single` is needed to display the sidebar according to minimal mistakes theme configuration.

Am I missing something?

**Comment by joshmoore** [comment]
That diff suggests only removing the line `permalink: /community/`. i.e., if the main page in subdirectories is "index.md" then you don't need to add the permalink. i.e.:

> `/community/` --> `/community/index.html`

automatically. And I think doing that by default makes things easier to understand for people working in the repository.

**Pull request merged**
