### PR TITLE
Add page for Zarr conventions

### PR DESCRIPTION
**Pull request by MSanKeys963**
Linking this from #80.

Added a new page for the public Zarr conventions. After merging this PR, it can be accessed at https://zarr.dev/conventions.

Let me know what you all think; suggestions are welcome. Thanks!

Screenshot 2023-05-21 at 14 09 35

### CODE REVIEW

**Comment by MSanKeys963** [comment]
Any feedback on this?

CC: @zarr-developers/steering-council @zarr-developers/python-core-devs @zarr-developers/implementation-council

**Comment by jbms** [comment]
This looks good to me!

**Comment by shoyer** [comment]
Maybe also add Xarray's Zarr convention? https://docs.xarray.dev/en/stable/internals/zarr-encoding-spec.html

**Comment by MSanKeys963** [comment]
If there's no additional feedback on this PR, I'd like to go ahead and merge this PR.

The current version can be seen here: https://zarr-developersgithubio--88.org.readthedocs.build/en/88/conventions/

Thanks!

**Comment by joshmoore** [comment]
:+1: Let's go for it.

**Pull request merged**
