### PR TITLE
Add blurb for community meetings

### PR DESCRIPTION
**Pull request by MSanKeys963**
Added blurb for community meetings on homepage.

### CODE REVIEW

**Comment by MSanKeys963** [comment]
Please have a look at this @joshmoore. Thanks!

**Comment by joshmoore** [comment]
The only caveat is likely that with the two links you add, there's the potential for misuse. With the zoom link, I assume we can manage. (It's easy enough now to lock people out, etc.) With the hackmd link, however, it will be difficult to detect if changes have occurred to old notes. This would increase my preference for moving (or at least backing up) to https://github.com/zarr-developers/community-calls

Otherwise, :100:

**Comment by MSanKeys963** [comment]
> With the hackmd link, however, it will be difficult to detect if changes have occurred to old notes.

I completely agree with this, in fact, I had this thought when opening this PR. I'm happy to create a `.md` file after every community call and push it to the `community calls` repo.

**Comment by joshmoore** [comment]
Sounds good. What's the next step then?

**Comment by MSanKeys963** [comment]
Let's merge this and I'll take care of the `.md` files for the community calls every 2 weeks.

**Pull request merged**
