### PR TITLE
Changed the outdated twitter logo

### LINKED ISSUE #104: Bug: Outdated Twitter Logo in Zarr homepage
** DESCRIPTION **
The Zarr webpage is currently using an outdated Twitter logo.

**Steps to Reproduce:**
1. Open the Zarr webpage .
2. Navigate to homepage .
3. Observe the outdated Twitter logo in footer.

Expected Result:
The Twitter logo should adhere to the most recent branding guidelines provided by Twitter.

Actual Result:
The current Twitter logo appears to be outdated and may not align with the latest branding standards.

https://github.com/zarr-developers/gsoc/assets/120818337/cae1044a-4a61-420e-b7c7-b427fbff4f70

### PR DESCRIPTION
**Pull request by AquibKhann**
closes #104 

This pull request addresses the outdated Twitter logo issue by replacing it with a more current and visually consistent icon. The new Twitter icon has been sourced from a licensed and suitable provider to ensure compliance with project licensing requirements.

### CODE REVIEW

**Comment by MSanKeys963** [comment]
Thanks for sending the PR, @AquibKhann.

Upon visiting https://zarr-developersgithubio--105.org.readthedocs.build/en/105/ and scrolling to the bottom, the Twitter (X) logo is not visible.

**Comment by AquibKhann** [comment]
working on it

**Comment by AquibKhann** [comment]
I have done the changes in the config.yml file but still the change is not being reflected. Did I need to make changes on some other files aswell ? can you please guide me .

**Comment by MSanKeys963** [comment]
Maybe this will work: https://fontawesome.com/icons/x-twitter?f=brands&s=solid?

**Comment by AquibKhann** [comment]
Thanks ! let me try

**Comment by AquibKhann** [comment]
I am unable to setup the environment for running the Zarr on my machine due to some security constraint I will make it happen by tomorrow , can you  tell me whether new PR make the changes visible or not .

**Comment by AquibKhann** [comment]
??

**Comment by joshmoore** [comment]
Not yet.
image


You can see the build under https://zarr-developersgithubio--105.org.readthedocs.build/en/105/ or by going to the job link:

image

**Comment by AquibKhann** [comment]
We were not using the current Font-awesome version that is why we were not able to see the changes .

https://github.com/zarr-developers/zarr-developers.github.io/assets/120818337/a467a4fb-5d1a-4809-a23e-8720849abc85

**Comment by MSanKeys963** [comment]
Nice catch, @AquibKhann.
Do you wanna push the new changes?

**Comment by AquibKhann** [comment]
??

**Comment by MSanKeys963** [comment]
I think you'd need to edit the `_utilities.scss` file to include the new version of logos. 

In the minimal mistakes repo, I can only see the old versions of the Twitter logo (check  [here](https://github.com/mmistakes/minimal-mistakes/blob/8a67ce8e41ec850f2d7c373aa47739b2abfee6f1/_sass/minimal-mistakes/_utilities.scss#L304); the logos are [this](https://fontawesome.com/v5/icons/twitter?f=brands&s=solid) and [this](https://fontawesome.com/v5/icons/twitter-square?f=brands&s=solid)). This is why the new logos are not rendering properly.

Also, the zarr-developers.github.io repository doesn't fork the Minimal Mistakes [repo](https://github.com/mmistakes/minimal-mistakes/). Instead, we're using the theme as a remote theme.
You can check out how to override theme defaults [here](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) and edit the `_utilities.scss` file to see if it works.

Let me know if there are more questions.

**Comment by AquibKhann** [comment]
I was facing some issues to setup the environment so that I can run the site on my machine i.e why I deletd the fork and wanted to start from zero.

**Comment by AquibKhann** [comment]
can you please help me out on how can I set up the environment on my machine

**Pull request closed without merging**
