### PR TITLE
Refresh of webpage

### LINKED ISSUE #29: Blog refresh
In preparation for changing the URL here from https://zarr-developers.github.io/ to  https://zarr.dev, here are some rebranding suggestions for turning the "blog" into the primary landing page for Zarr:

## Outline/sitemap

- [ ] Landing page
  - [ ] Job opening
  - [x] Content from one pager
  - [ ] Super simple example
  - [ ] Drawings of what’s in a zarr https://twitter.com/notjustmoore/status/1465391574360207360/photo/1 
  - [ ] Projects using
  - [x] Embed video from Alistair
- [ ] Implementations
  - Related projects
  - N5
  - Exdir
- [ ] Projects using
  - [ ] Pangeo (--> Python?)
- [ ] Related libraries
  - [ ] Dask & xarray (--> Python?)
- [ ] About
  - Funding
  - Repositories
    - https://github.com/zarr-developers/community/issues?page=2&q=is%3Aissue+is%3Aopen
  - Steering council
- [ ] Slides
  - https://github.com/zarr-developers/community/issues/10 
- [ ] Artwork
  - https://github.com/zarr-developers/community/issues/11 
- [ ] Getting in touch
  - [x] https://github.com/zarr-developers/community/issues/1 
  - [x] Calendar
  - [ ] Stackoverflow(?)
  - [x] Gitter
  - [ ] Migrate notes from gdocs (hackmd?)
- [ ] Posts (Blog)
  - In the news: https://github.com/zarr-developers/community/issues/4 
  - Publications (retro-actively?)
  - New logo & url (thanks to NumFOCUS)
  - Job opening
  - tweets (reverse chronological)
    - https://twitter.com/opengeospatial/status/1466732898523004928
    - https://twitter.com/zarr_dev/status/1466789015357739010
    - https://twitter.com/notjustmoore/status/1432795729890877441
    - https://twitter.com/GerBI_GMB/status/1432747023715942407
    - https://twitter.com/carbonplanorg/status/1442559369539817478
    - https://twitter.com/ChelleGentemann/status/1427654394867183626
    - https://twitter.com/AbiIsNotABot/status/1334114956380229632
    - ...

## Other TODOs
- [x] favicon

cc: @zarr-developers/steering-council

### PR DESCRIPTION
**Pull request by joshmoore**
fix #29

### CODE REVIEW

**Comment by joshmoore** [comment]
While preparing to set the CNAME for this repository, I realized that the old pages will not redirect to the new ones:
```
https://zarr-developers.github.io/about/ --> https://zarr.dev/about
```
Options:
 * don't worry about the redirects. (lose google ranking, etc.)
 * leave this repo as is and create a new https://github.com/zarr-developers/zarr.dev one, redirecting manually (maybe the best?)
 * keep this URL but have zarr.dev redirect here (older, longer URLs hang around)
 * put a proxy at zarr.dev and dynamically host this content (needs work)

**Comment by joshmoore** [comment]
https://zarr.dev/ is live as a copy as an example of option 2 but the redirection is not yet in place.

**Comment by jakirkham** [comment]
Just to confirm how were you setting the CNAME?

**Comment by jakirkham** [comment]
When we made this change in conda-forge (which was a while back and my memory is fuzzy) ( https://github.com/conda-forge/conda-forge.github.io/pull/402 ), we added an entry to Cloudflare to handle redirections. Guessing we need to do something similar here?

**Comment by joshmoore** [comment]
> Guessing we need to do something similar here with Namecheap?

Since the old site is github.io I don't think we will be able to do anything at the DNS level.

**Comment by joshmoore** [comment]
> Just to confirm how were you setting the CNAME?

by setting a CNAME here: https://github.com/zarr-developers/zarr.dev/blob/main/CNAME

**Comment by jakirkham** [comment]
We may also need to configure things on this page. In particular ["Custom domain"]( https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site ) to be the domain we want

https://github.com/zarr-developers/zarr-developers.github.io/settings/pages

**Comment by joshmoore** [comment]
> We may also need to configure things on this page. In particular ["Custom domain"](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site) to be the domain we want


That will be an option 1 scenario. https://zarr-developers.github.io/ as it currently exists will no longer be reachable, breaking google searches, etc.

**Comment by jakirkham** [comment]
Sorry maybe I'm missing something. Was trying to see if we could get to 4. The suggestion above may not be all of the story, but perhaps part of what is needed

**Comment by jakirkham** [comment]
Guessing we want [301 from this page]( https://www.namecheap.com/support/knowledgebase/article.aspx/385/2237/how-to-redirect-a-url-for-a-domain/ ), but feel free to correct me if I'm missing something

**Comment by joshmoore** [comment]
Agreed, but I don't know anyway to do that at the site level. https://github.com/zarr-developers/zarr-developers.github.io/pull/32 will do it page for page which is what we did here: https://github.com/ome/blog/pull/75

**Comment by jakirkham** [comment]
I _think_ individual sites under the domain reroute automatically after putting in the domain redirection

For example with conda-forge, https://conda-forge.github.io/docs -> https://conda-forge.org/docs

Though maybe I'm misunderstanding the question

**Comment by joshmoore** [comment]
I think that's correct just _we_ can't do that for something we don't own (github.io)

**Comment by jakirkham** [comment]
For clarity, this also works https://conda-forge.github.io/ -> https://conda-forge.org/

Though maybe I'm still not following the concern being raised. Could you please share an example of the kind of thing we are concerned about not working here?

**Comment by joshmoore** [comment]
> For clarity, this also works https://conda-forge.github.io/ -> https://conda-forge.org/

@jakirkham: do other sub-pages from conda-forge.github.io redirect?

**Comment by joshmoore** [comment]
Update:
 - I disabled github.com/zarr-developers/zarr.dev --> https://zarr.dev
 - Pushed a CNAME of "zarr.dev" to zarr-developers.github.io
 - The redirects worked as John promised (*as long as* this repo's name never changes!)
 - Then I merged the zarr.dev branch into the mainline here, completing the refresh.

**Comment by jakirkham** [comment]
That's great! 🎉 Thanks Josh 😀

**Comment by jakirkham** [comment]
Updated the GitHub org URL to link directly to https://zarr.dev ( instead of https://zarr-developers.github.io as it was previously )

Screen Shot 2022-06-01 at 2 17 50 AM

**Comment by MSanKeys963** [comment]
Thanks, @jakirkham.

**Pull request merged**
