### PR TITLE
Add Zarr Twitter account

### PR DESCRIPTION
**Pull request by jrbourbeau**
We're on Twitter now!

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Thanks for reviewing @mzjp2 : )

**Comment by joshmoore** [comment]
:+1: while we're doing marketing, I went ahead and propagated to the GitHub profile:

Screen Shot 2020-03-27 at 09 04 49

Now just need some more content on http://zarr-developers.github.io so we can tweet it ;)

**Comment by alimanfoo** [comment]
Awesome!

> Now just need some more content on http://zarr-developers.github.io so we can tweet it ;)

Yeah, seriously let me know if anyone has suggestions for some shortish blog posts that could go there, happy to help bash something together. Some possibilities:

* Blog post including the scipy 2019 zarr talk, optionally with any other commentary or links to other relevant scipy material 
* Blog post about the zarr-python 2.4 release 
* Blog post updating on the CZI EOSS plans, and/or about the EOSS kick-off

**Comment by alimanfoo** [comment]
* Blog post about the cool and unanticipated ways that people have been hacking around with zarr lately (I really like emphasizing the hackability of zarr, communicating that that is a central design goal is a nice thing IMHO)

**Comment by mzjp2** [comment]
Once the governance stuff gets merged in, maybe a blog post announcing our governing model and how contributions work going forward?

**Comment by jrbourbeau** [comment]
Adding more content to the website would be great! I've collected the blog post ideas here over in a separate issue so we can continue to track progress and add more ideas (xref https://github.com/zarr-developers/zarr-developers.github.io/issues/15)

**Comment by joshmoore** [comment]
If you omit `latest` from RTD, it now redirects to https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/ to make it explicit. We may want to move `stable` to point at `master` and have `latest` point at `v3.0` or `dev` or whatever we will be using going down the road.

**Pull request merged**
